force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Type</label>
    <referenceTo>Type__c</referenceTo>
    <relationshipLabel>Pokemons</relationshipLabel>
    <relationshipName>Pokemons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Type__c/Type__c.object-meta.xml
<CustomObject>
    <label>Type</label>
    <nameField>
        <label>Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Type__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokemon</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Types</relationshipLabel>
    <relationshipName>Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Weakness__c/Weakness__c.object-meta.xml
<CustomObject>
    <label>Weakness</label>
    <nameField>
        <label>Weakness Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weaknesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Weakness__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <label>Pokemon</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Weaknesses</relationshipLabel>
    <relationshipName>Weaknesses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PostInstallScript.cls
/**
 * @description       : 
 * @author            : Ana Cabrera
 * @group             : 
 * @last modified on  : 11-24-2021
 * @last modified by  : Ana Cabrera
**/
global with sharing class PostInstallScript implements InstallHandler {
    global PostInstallScript() {}
    global void onInstall(InstallContext context) {
        createDemoData();
    }

    static void deleteDemoData() {
        Database.delete([SELECT Id FROM Pokemon__c]);
        Database.delete([SELECT Id FROM Type__c]);
        Database.delete([SELECT Id FROM Weakness__c]);
    }

    static void createDemoData() {
        new LoadData(Pokemon__c.SObjectType,'PokemonData');
        new LoadData(Type__c.SObjectType,'PokemonTypeData');
        new LoadData(Weakness__c.SObjectType,'PokemonWeaknessData');
    }
}